import React, { useCallback, useEffect, useState } from 'react';
import { CButton, CCard, CCardBody, CCardHeader, CCol, CFormSelect, CRow } from '@coreui/react';
import { Link } from 'react-router-dom';
import { getFollowUpWorkQueue, getFollowUpWorkQueueSummary } from '../../services/Apis/crm';
import { apiMessage, ErrorState, formatDate, LoadingState, PaginationControls } from '../Crm/common';

const groups = ['OVERDUE', 'DUE_TODAY', 'UPCOMING', 'COMPLETED_TODAY', 'LEADS_WITHOUT_PENDING_FOLLOW_UP'];
const DailyQueue = ({ admin, counsellors, onEdit, onComplete, onCancel, refreshToken }) => {
  const [group, setGroup] = useState('OVERDUE'); const [assignedCounsellorId, setAssignedCounsellorId] = useState(''); const [items, setItems] = useState([]); const [summary, setSummary] = useState({}); const [pagination, setPagination] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = useCallback(async (page = 1) => { setLoading(true); try { const params = { group, page, pageSize: 25, ...(assignedCounsellorId ? { assignedCounsellorId } : {}) }; const [queue, totals] = await Promise.all([getFollowUpWorkQueue(params), getFollowUpWorkQueueSummary(assignedCounsellorId ? { assignedCounsellorId } : {})]); setItems(queue.data.data); setPagination(queue.data.pagination); setSummary(totals.data.data); setError(''); } catch (e) { setError(apiMessage(e, 'Daily work queue could not be loaded.')); } finally { setLoading(false); } }, [group, assignedCounsellorId]);
  useEffect(() => { load(); }, [load, refreshToken]);
  return <CCard className="crm-section"><CCardHeader>Daily priority queue</CCardHeader><CCardBody>{error && <ErrorState message={error} onRetry={load}/>}<CRow className="g-2 mb-3">{groups.map((item) => <CCol key={item}><CButton variant={group === item ? undefined : 'outline'} className="w-100" onClick={() => setGroup(item)}>{item.replaceAll('_', ' ')}<br/><strong>{summary[item] || 0}</strong></CButton></CCol>)}</CRow>{admin && <CFormSelect className="mb-3" aria-label="Queue counsellor" value={assignedCounsellorId} onChange={(e) => setAssignedCounsellorId(e.target.value)}><option value="">All counsellors</option>{counsellors.map((person) => <option key={person.id} value={person.id}>{person.displayName}</option>)}</CFormSelect>}{loading ? <LoadingState/> : <><div className="table-responsive"><table className="table"><thead><tr><th>Contact</th><th>Phone</th><th>Lead</th><th>Task</th><th>Due / activity</th><th/></tr></thead><tbody>{items.map((item) => <tr key={item.task?.id || item.lead?.id} className={item.queueGroup === 'OVERDUE' ? 'table-warning' : ''}><td><Link to={`/contacts/${item.contact.id}`}>{item.contact.displayName || 'Contact'}</Link></td><td>{item.contact.normalizedPhone || '—'}</td><td>{item.lead.status || '—'}</td><td>{item.task ? <>{item.task.type} · <strong className={item.task.priority === 'HIGH' || item.task.priority === 'URGENT' ? 'text-danger' : ''}>{item.task.priority}</strong></> : 'No pending follow-up'}</td><td>{item.task ? formatDate(item.task.dueAt, true) : formatDate(item.lead.lastActivityAt, true)}</td><td>{item.task ? <><CButton size="sm" variant="outline" onClick={() => onEdit(item.task)}>Edit</CButton>{' '}<CButton size="sm" color="success" onClick={() => onComplete(item.task)}>Complete</CButton>{' '}<CButton size="sm" color="danger" variant="outline" onClick={() => onCancel(item.task)}>Cancel</CButton></> : <CButton component={Link} size="sm" to={`/contacts/${item.contact.id}`}>Create follow-up</CButton>}</td></tr>)}</tbody></table></div><PaginationControls pagination={pagination} onPage={load}/></>}</CCardBody></CCard>;
};
export default DailyQueue;
