import React, { useCallback, useEffect, useState } from 'react';
import { CAlert, CButton, CCard, CCardBody, CCardHeader, CCol, CFormInput, CFormLabel, CFormSelect, CModal, CModalBody, CModalHeader, CModalTitle, CRow } from '@coreui/react';
import { Link } from 'react-router-dom';
import { useAuth } from '../../auth/AuthProvider';
import { cancelFollowUp, completeFollowUp, getContact, listCounsellorOptions, listFollowUps, updateFollowUp } from '../../services/Apis/crm';
import { apiMessage, ErrorState, formatDate, LoadingState } from '../Crm/common';
import '../Crm/crm.css';
import { FOLLOW_UP_PRIORITIES, FOLLOW_UP_TYPES, FollowUpForm } from './FollowUpForm';
import CompletionForm from './CompletionForm';

const statuses = ['PENDING', 'COMPLETED', 'CANCELLED'];
const initialFilters = { assignedCounsellorId: '', status: '', type: '', priority: '', dueFrom: '', dueTo: '', overdue: false, search: '' };
const isOverdue = (task) => task.status === 'PENDING' && new Date(task.dueAt) < new Date();
const taskLabel = (task, contacts) => contacts[task.contactId]?.displayName || `Contact ${task.contactId}`;

const FollowUps = () => {
  const { user } = useAuth(); const admin = user?.role === 'SUPER_ADMIN';
  const [tasks, setTasks] = useState([]); const [pagination, setPagination] = useState(null); const [filters, setFilters] = useState(initialFilters);
  const [counsellors, setCounsellors] = useState([]); const [contacts, setContacts] = useState({}); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [editing, setEditing] = useState(null); const [completing, setCompleting] = useState(null);
  const load = useCallback(async (page = 1) => { setLoading(true); setError(''); try { const params = { page, pageSize: 25, ...Object.fromEntries(Object.entries(filters).filter(([, value]) => value !== '' && value !== false)) }; const response = await listFollowUps(params); const nextTasks = response.data.data; setTasks(nextTasks); setPagination(response.data.pagination); const contactResponses = await Promise.allSettled([...new Set(nextTasks.map((task) => task.contactId))].map((id) => getContact(id))); setContacts(Object.fromEntries(contactResponses.filter((result) => result.status === 'fulfilled').map((result) => [result.value.data.data.contact.id, result.value.data.data.contact]))); if (admin) { const people = await listCounsellorOptions(); setCounsellors(people.data.data); } } catch (e) { setError(apiMessage(e, 'Follow-ups could not be loaded.')); } finally { setLoading(false); } }, [filters, admin]);
  useEffect(() => { load(); }, [load]);
  const updateFilter = (key, value) => setFilters((current) => ({ ...current, [key]: value }));
  const save = async (payload) => { setSaving(true); setError(''); try { const { id, version } = editing; const body = { version, type: payload.type, priority: payload.priority, purpose: payload.purpose, internalNote: payload.internalNote, dueAt: payload.dueAt }; if (admin) body.assignedCounsellorId = payload.assignedCounsellorId; if (admin && payload.assignedCounsellorId !== editing.assignedCounsellorId && !window.confirm('Confirm reassignment of this follow-up?')) return; await updateFollowUp(id, body); setEditing(null); setMessage('Follow-up updated.'); await load(pagination?.page || 1); } catch (e) { setError(apiMessage(e, 'Follow-up could not be updated.')); } finally { setSaving(false); } };
  const action = async (task, kind) => { if (kind === 'complete') { setCompleting(task); return; } if (!window.confirm('Confirm cancel this follow-up?')) return; setSaving(true); try { await cancelFollowUp(task.id, { version: task.version }); setMessage('Follow-up cancelled.'); await load(pagination?.page || 1); } catch (e) { setError(apiMessage(e, 'Follow-up could not be cancelled.')); } finally { setSaving(false); } };
  const submitCompletion = async (payload) => { setSaving(true); try { await completeFollowUp(completing.id, payload); setCompleting(null); setMessage('Follow-up completed.'); await load(pagination?.page || 1); } catch (e) { setError(apiMessage(e, 'Follow-up could not be completed.')); } finally { setSaving(false); } };
  if (loading && !tasks.length) return <LoadingState label="Loading follow-ups…" />;
  return <main className="crm-page"><div className="crm-page-header"><div><h1>Follow-ups</h1><p>Tasks are visible only within your current Lead assignment.</p></div></div>{message && <CAlert color="success">{message}</CAlert>}{error && <ErrorState message={error} onRetry={() => load(pagination?.page || 1)} />}
    <CCard className="crm-section"><CCardHeader>Filters</CCardHeader><CCardBody><CRow className="g-2"><CCol md={3}><CFormLabel>Search Contact or Lead</CFormLabel><CFormInput value={filters.search} onChange={(e) => updateFilter('search', e.target.value)} /></CCol>{admin && <CCol md={3}><CFormLabel>Assigned counsellor</CFormLabel><CFormSelect value={filters.assignedCounsellorId} onChange={(e) => updateFilter('assignedCounsellorId', e.target.value)}><option value="">All</option>{counsellors.map((person) => <option value={person.id} key={person.id}>{person.displayName}</option>)}</CFormSelect></CCol>}<CCol md={2}><CFormLabel>Status</CFormLabel><CFormSelect value={filters.status} onChange={(e) => updateFilter('status', e.target.value)}><option value="">All</option>{statuses.map((value) => <option key={value}>{value}</option>)}</CFormSelect></CCol><CCol md={2}><CFormLabel>Type</CFormLabel><CFormSelect value={filters.type} onChange={(e) => updateFilter('type', e.target.value)}><option value="">All</option>{FOLLOW_UP_TYPES.map((value) => <option key={value}>{value}</option>)}</CFormSelect></CCol><CCol md={2}><CFormLabel>Priority</CFormLabel><CFormSelect value={filters.priority} onChange={(e) => updateFilter('priority', e.target.value)}><option value="">All</option>{FOLLOW_UP_PRIORITIES.map((value) => <option key={value}>{value}</option>)}</CFormSelect></CCol><CCol md={3}><CFormLabel>Due from</CFormLabel><CFormInput type="date" value={filters.dueFrom} onChange={(e) => updateFilter('dueFrom', e.target.value ? new Date(`${e.target.value}T00:00`).toISOString() : '')} /></CCol><CCol md={3}><CFormLabel>Due to</CFormLabel><CFormInput type="date" value={filters.dueTo} onChange={(e) => updateFilter('dueTo', e.target.value ? new Date(`${e.target.value}T23:59`).toISOString() : '')} /></CCol><CCol md={2}><CFormLabel>Overdue only</CFormLabel><CFormSelect value={String(filters.overdue)} onChange={(e) => updateFilter('overdue', e.target.value === 'true')}><option value="false">No</option><option value="true">Yes</option></CFormSelect></CCol><CCol md={2} className="d-flex align-items-end gap-2"><CButton onClick={() => load(1)}>Apply</CButton><CButton variant="outline" onClick={() => setFilters(initialFilters)}>Clear</CButton></CCol></CRow></CCardBody></CCard>
    <CCard className="crm-section"><CCardHeader>Task list</CCardHeader><CCardBody>{!tasks.length ? <p className="text-muted">No follow-ups match these filters.</p> : <div className="table-responsive"><table className="table"><thead><tr><th>Contact</th><th>Counsellor</th><th>Type</th><th>Priority</th><th>Due</th><th>Status</th><th>Purpose / outcome</th><th /></tr></thead><tbody>{tasks.map((task) => <tr key={task.id} className={isOverdue(task) ? 'table-warning' : ''}><td><Link to={`/contacts/${task.contactId}`}>{taskLabel(task, contacts)}</Link></td><td>{counsellors.find((person) => person.id === task.assignedCounsellorId)?.displayName || (task.assignedCounsellorId === user?.id ? 'You' : task.assignedCounsellorId)}</td><td>{task.type}</td><td>{task.priority}</td><td>{formatDate(task.dueAt, true)} {isOverdue(task) && <strong className="text-danger d-block">Overdue</strong>}</td><td>{task.status}</td><td>{task.purpose}{task.outcome && <small className="d-block text-muted">{task.outcome}: {task.discussionSummary || '—'}</small>}</td><td className="text-nowrap">{task.status === 'PENDING' && <><CButton size="sm" variant="outline" onClick={() => setEditing(task)}>Edit</CButton>{' '}<CButton size="sm" color="success" disabled={saving} onClick={() => action(task, 'complete')}>Complete</CButton>{' '}<CButton size="sm" color="danger" variant="outline" disabled={saving} onClick={() => action(task, 'cancel')}>Cancel</CButton></>}</td></tr>)}</tbody></table></div>}{pagination && <div className="d-flex gap-2"><CButton variant="outline" disabled={!pagination.hasPrevious} onClick={() => load(pagination.page - 1)}>Previous</CButton><span className="align-self-center">Page {pagination.page}</span><CButton variant="outline" disabled={!pagination.hasNext} onClick={() => load(pagination.page + 1)}>Next</CButton></div>}</CCardBody></CCard>
    <CModal visible={Boolean(editing)} onClose={() => setEditing(null)}><CModalHeader><CModalTitle>Edit follow-up</CModalTitle></CModalHeader><CModalBody>{editing && <FollowUpForm task={editing} admin={admin} counsellors={counsellors} assignedCounsellorId={editing.assignedCounsellorId} onSubmit={save} saving={saving} submitLabel="Save follow-up" />}</CModalBody></CModal>
    <CModal visible={Boolean(completing)} onClose={() => setCompleting(null)}><CModalHeader><CModalTitle>Complete follow-up</CModalTitle></CModalHeader><CModalBody>{completing && <CompletionForm task={completing} saving={saving} error={error} onSubmit={submitCompletion} />}</CModalBody></CModal>
  </main>;
};
export default FollowUps;
