import React, { useCallback, useEffect, useState } from 'react';
import { CAlert, CButton, CCard, CCardBody, CCardHeader, CCol, CFormInput, CFormLabel, CFormSelect, CRow, CTable, CTableBody, CTableDataCell, CTableHead, CTableHeaderCell, CTableRow } from '@coreui/react';

import { listWhatsAppBroadcasts } from '../../services/Apis/crm';
import { apiMessage, EmptyState, LoadingState, PaginationControls } from '../Crm/common';

const states = ['DRAFT', 'PREPARING', 'CONFIRMED', 'EXECUTING', 'PAUSED_RETRYABLE', 'COMPLETED', 'CANCELLED'];
const schedulerStates = ['UNSCHEDULED', 'SCHEDULED', 'RUNNING', 'WAITING_RETRY', 'COMPLETED', 'CANCELLED'];
const formatTime = (value) => value ? new Date(value).toLocaleString() : '—';
const isoDate = (value, endOfDay = false) => value ? new Date(`${value}T${endOfDay ? '23:59:59.999' : '00:00:00'}`).toISOString() : undefined;

const BroadcastHistory = ({ onOpen }) => {
  const [filters, setFilters] = useState({ state: '', schedulerState: '', templateName: '', createdFrom: '', createdTo: '' });
  const [rows, setRows] = useState([]); const [pagination, setPagination] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = useCallback(async (page = 1, activeFilters = filters) => { const query = { page, pageSize: 25, ...(activeFilters.state ? { state: activeFilters.state } : {}), ...(activeFilters.schedulerState ? { schedulerState: activeFilters.schedulerState } : {}), ...(activeFilters.templateName.trim() ? { templateName: activeFilters.templateName.trim() } : {}), ...(activeFilters.createdFrom ? { createdFrom: isoDate(activeFilters.createdFrom) } : {}), ...(activeFilters.createdTo ? { createdTo: isoDate(activeFilters.createdTo, true) } : {}) }; setLoading(true); setError(''); try { const response = await listWhatsAppBroadcasts(query); setRows(response.data.data || []); setPagination(response.data.pagination || null); } catch (requestError) { setError(apiMessage(requestError, 'Broadcast history could not be loaded.')); } finally { setLoading(false); } }, [filters]);
  useEffect(() => { (async () => { try { const response = await listWhatsAppBroadcasts({ page: 1, pageSize: 25 }); setRows(response.data.data || []); setPagination(response.data.pagination || null); } catch (requestError) { setError(apiMessage(requestError, 'Broadcast history could not be loaded.')); } finally { setLoading(false); } })(); }, []);
  const clear = () => { const cleared = { state: '', schedulerState: '', templateName: '', createdFrom: '', createdTo: '' }; setFilters(cleared); load(1, cleared); };

  return <CCard className="crm-section"><CCardHeader>Broadcast History</CCardHeader><CCardBody>
    {error && <CAlert color="danger">{error}<CButton size="sm" className="ms-2" variant="outline" color="danger" onClick={() => load()}>Retry</CButton></CAlert>}
    <CRow className="g-2 mb-3"><CCol md={3}><CFormLabel htmlFor="history-state">Broadcast state</CFormLabel><CFormSelect id="history-state" value={filters.state} onChange={(event) => setFilters({ ...filters, state: event.target.value })}><option value="">All states</option>{states.map((state) => <option key={state}>{state}</option>)}</CFormSelect></CCol><CCol md={3}><CFormLabel htmlFor="history-scheduler-state">Scheduler state</CFormLabel><CFormSelect id="history-scheduler-state" value={filters.schedulerState} onChange={(event) => setFilters({ ...filters, schedulerState: event.target.value })}><option value="">All scheduler states</option>{schedulerStates.map((state) => <option key={state}>{state}</option>)}</CFormSelect></CCol><CCol md={3}><CFormLabel htmlFor="history-template">Template name</CFormLabel><CFormInput id="history-template" value={filters.templateName} onChange={(event) => setFilters({ ...filters, templateName: event.target.value })}/></CCol><CCol md={3}><CFormLabel htmlFor="history-from">Created from</CFormLabel><CFormInput id="history-from" type="date" value={filters.createdFrom} onChange={(event) => setFilters({ ...filters, createdFrom: event.target.value })}/></CCol><CCol md={3}><CFormLabel htmlFor="history-to">Created to</CFormLabel><CFormInput id="history-to" type="date" value={filters.createdTo} onChange={(event) => setFilters({ ...filters, createdTo: event.target.value })}/></CCol><CCol md={3} className="d-flex align-items-end"><CButton onClick={() => load(1)} disabled={loading}>Apply filters</CButton><CButton className="ms-2" variant="outline" onClick={clear} disabled={loading}>Clear filters</CButton></CCol></CRow>
    {loading ? <LoadingState label="Loading broadcast history…"/> : !rows.length ? <EmptyState title="No broadcasts match these filters" detail="Clear or adjust the filters to view historical broadcasts."/> : <><CTable responsive><CTableHead><CTableRow><CTableHeaderCell>Template</CTableHeaderCell><CTableHeaderCell>State</CTableHeaderCell><CTableHeaderCell>Schedule</CTableHeaderCell><CTableHeaderCell>Created</CTableHeaderCell><CTableHeaderCell>Preparation</CTableHeaderCell><CTableHeaderCell>Execution</CTableHeaderCell><CTableHeaderCell>Delivery</CTableHeaderCell><CTableHeaderCell>Action</CTableHeaderCell></CTableRow></CTableHead><CTableBody>{rows.map((row) => <CTableRow key={row.id}><CTableDataCell><strong>{row.template?.name || 'Unnamed template'}</strong><br/><small>{row.template?.language || '—'} · {row.template?.category || '—'}</small></CTableDataCell><CTableDataCell>{row.state}</CTableDataCell><CTableDataCell>{row.schedulerState}<br/><small>{formatTime(row.scheduledFor)}</small></CTableDataCell><CTableDataCell>{formatTime(row.createdAt)}<br/><small>{row.createdBy?.displayName || row.createdBy?.email || 'Unknown'}</small></CTableDataCell><CTableDataCell>P {row.preparationTotals?.prepared || 0} · E {row.preparationTotals?.eligible || 0}<br/><small>S {row.preparationTotals?.skipped || 0} · R {row.preparationTotals?.rejected || 0}</small></CTableDataCell><CTableDataCell>P {row.executionTotals?.pending || 0} · A {row.executionTotals?.accepted || 0}<br/><small>F {row.executionTotals?.failed || 0} · R {row.executionTotals?.remaining || 0}</small></CTableDataCell><CTableDataCell>Delivered {row.deliveryTotals?.delivered || 0}<br/><small>Read {row.deliveryTotals?.read || 0}</small></CTableDataCell><CTableDataCell><CButton size="sm" onClick={() => onOpen(row.id)}>Open</CButton></CTableDataCell></CTableRow>)}</CTableBody></CTable><PaginationControls pagination={pagination} onPage={load}/></>}</CCardBody></CCard>;
};

export default BroadcastHistory;
