import React, { useEffect, useMemo, useState } from 'react';
import { CAlert, CButton, CCard, CCardBody, CCardHeader, CFormInput, CFormLabel, CFormSelect, CRow, CCol, CTable, CTableBody, CTableDataCell, CTableHead, CTableHeaderCell, CTableRow } from '@coreui/react';

import { createWhatsAppBroadcast, deleteWhatsAppBroadcast, listWhatsAppBroadcastRecipients, listWhatsAppTemplates, prepareWhatsAppBroadcast } from '../../services/Apis/crm';
import { apiMessage, EmptyState, ErrorState, LoadingState, PaginationControls } from '../Crm/common';
import TemplatePreview from '../WhatsAppTemplates/TemplatePreview';
import '../Crm/crm.css';

const CONTACT_FIELDS = [['firstName', 'First name'], ['lastName', 'Last name'], ['displayName', 'Display name'], ['email', 'Email'], ['city', 'City'], ['state', 'State'], ['normalizedPhone', 'Phone'], ['source', 'Source']];
const LEAD_FIELDS = [['status', 'Status'], ['priority', 'Priority'], ['source', 'Source'], ['preferredMode', 'Preferred mode'], ['targetExamYear', 'Target exam year'], ['coursePreference', 'Course preference']];
const variablePattern = /{{\s*(\d+)\s*}}/g;

const templateVariables = (template) => {
  const variables = [];
  const add = (text) => [...new Set([...String(text || '').matchAll(variablePattern)].map((match) => Number(match[1])))].sort((a, b) => a - b).forEach((position) => variables.push(position));
  (template?.headers || []).forEach((header) => add(header.text)); add(template?.body?.text); (template?.buttons || []).forEach((button) => add(button.url));
  return variables;
};
const initialMapping = () => ({ source: 'CONTACT', field: 'firstName', value: '' });

const WhatsAppBroadcasts = () => {
  const [templates, setTemplates] = useState([]); const [templateId, setTemplateId] = useState(''); const [filters, setFilters] = useState({ city: '', leadStatus: '', priority: '', preferredMode: '', targetExamYear: '' });
  const [mappings, setMappings] = useState([]); const [broadcast, setBroadcast] = useState(null); const [tab, setTab] = useState('ELIGIBLE'); const [recipients, setRecipients] = useState([]); const [pagination, setPagination] = useState(null);
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const selected = useMemo(() => templates.find((template) => template.id === templateId), [templates, templateId]);
  const required = useMemo(() => templateVariables(selected), [selected]);

  useEffect(() => { (async () => { try { const response = await listWhatsAppTemplates({ page: 1, pageSize: 100 }); setTemplates(response.data.data || []); } catch (requestError) { setError(apiMessage(requestError, 'Approved templates could not be loaded.')); } finally { setLoading(false); } })(); }, []);
  useEffect(() => { setMappings(required.map(initialMapping)); }, [templateId, required]);
  const loadRecipients = async (status = tab, page = 1) => { if (!broadcast) return; setBusy(true); try { const response = await listWhatsAppBroadcastRecipients(broadcast.id, { status, page, pageSize: 25 }); setRecipients(response.data.data || []); setPagination(response.data.pagination || null); } catch (requestError) { setError(apiMessage(requestError, 'Recipient previews could not be loaded.')); } finally { setBusy(false); } };
  const updateMapping = (index, patch) => setMappings((current) => current.map((mapping, item) => item === index ? { ...mapping, ...patch } : mapping));
  const payload = () => ({ templateId, recipientFilters: { contact: { ...(filters.city ? { city: filters.city } : {}) }, lead: { ...(filters.leadStatus ? { status: filters.leadStatus } : {}), ...(filters.priority ? { priority: filters.priority } : {}), ...(filters.preferredMode ? { preferredMode: filters.preferredMode } : {}), ...(filters.targetExamYear ? { targetExamYear: Number(filters.targetExamYear) } : {}) } }, variableMappings: mappings.map((mapping) => mapping.source === 'FIXED' ? { source: 'FIXED', value: mapping.value } : { source: mapping.source, field: mapping.field }) });
  const create = async () => { if (!templateId || mappings.some((mapping) => mapping.source === 'FIXED' && !mapping.value.trim())) { setError('Select a template and complete every fixed variable value.'); return; } setBusy(true); setError(''); try { const response = await createWhatsAppBroadcast(payload()); setBroadcast(response.data.data); setNotice('Draft created. Prepare recipients to review the immutable previews.'); } catch (requestError) { setError(apiMessage(requestError, 'The broadcast draft could not be created.')); } finally { setBusy(false); } };
  const prepare = async () => { setBusy(true); setError(''); try { const response = await prepareWhatsAppBroadcast(broadcast.id, broadcast.version); const updated = response.data.data; setBroadcast(updated); setNotice('Recipient preview prepared from the current Contact and Lead data.'); await loadRecipients('ELIGIBLE'); } catch (requestError) { const conflict = requestError.response?.status === 409; setError(conflict ? 'This draft changed elsewhere. Refresh the draft before preparing again.' : apiMessage(requestError, 'Recipients could not be prepared.')); } finally { setBusy(false); } };
  const remove = async () => { if (!window.confirm('Delete this unchanged broadcast draft?')) return; setBusy(true); try { await deleteWhatsAppBroadcast(broadcast.id, broadcast.version); setBroadcast(null); setRecipients([]); setNotice('Draft deleted.'); } catch (requestError) { setError(requestError.response?.status === 409 ? 'This draft changed elsewhere. Refresh before deleting.' : apiMessage(requestError, 'The draft could not be deleted.')); } finally { setBusy(false); } };
  const chooseTab = (status) => { setTab(status); loadRecipients(status); };

  if (loading) return <LoadingState label="Loading approved templates…" />;
  return <main className="crm-page"><div className="crm-page-header"><div><h1>WhatsApp Broadcasts</h1><p>Create and verify recipient previews only. No message is sent from this screen.</p></div></div>
    {error && <ErrorState message={error} onRetry={() => setError('')} />}{notice && <CAlert color="success">{notice}</CAlert>}
    {!broadcast ? <CCard className="crm-section"><CCardHeader>Create broadcast draft</CCardHeader><CCardBody>
      {!templates.length ? <EmptyState title="No approved templates available" detail="Synchronize approved templates before creating a broadcast." /> : <><CRow className="g-3"><CCol md={6}><CFormLabel htmlFor="broadcast-template">Approved template</CFormLabel><CFormSelect id="broadcast-template" value={templateId} onChange={(event) => setTemplateId(event.target.value)}><option value="">Choose a template</option>{templates.map((template) => <option key={template.id} value={template.id}>{template.name} · {template.language} · {template.category}</option>)}</CFormSelect></CCol><CCol md={3}><CFormLabel htmlFor="filter-city">Contact city</CFormLabel><CFormInput id="filter-city" value={filters.city} onChange={(event) => setFilters({ ...filters, city: event.target.value })} /></CCol><CCol md={3}><CFormLabel htmlFor="filter-status">Lead status</CFormLabel><CFormInput id="filter-status" value={filters.leadStatus} onChange={(event) => setFilters({ ...filters, leadStatus: event.target.value })} /></CCol><CCol md={3}><CFormLabel htmlFor="filter-priority">Lead priority</CFormLabel><CFormInput id="filter-priority" value={filters.priority} onChange={(event) => setFilters({ ...filters, priority: event.target.value })} /></CCol><CCol md={3}><CFormLabel htmlFor="filter-mode">Preferred mode</CFormLabel><CFormInput id="filter-mode" value={filters.preferredMode} onChange={(event) => setFilters({ ...filters, preferredMode: event.target.value })} /></CCol><CCol md={3}><CFormLabel htmlFor="filter-year">Target exam year</CFormLabel><CFormInput id="filter-year" type="number" value={filters.targetExamYear} onChange={(event) => setFilters({ ...filters, targetExamYear: event.target.value })} /></CCol></CRow>
      {selected && <><hr/><h2 className="h5">Template preview</h2><TemplatePreview template={selected} /><h2 className="h5 mt-4">Ordered variable mappings</h2>{required.length ? mappings.map((mapping, index) => <CRow className="g-2 mb-2" key={index}><CCol md={3}><CFormLabel>Variable {index + 1}</CFormLabel><CFormInput value={`{{${required[index]}}}`} disabled /></CCol><CCol md={3}><CFormLabel>Source</CFormLabel><CFormSelect aria-label={`Variable source ${index + 1}`} value={mapping.source} onChange={(event) => updateMapping(index, { source: event.target.value, field: event.target.value === 'LEAD' ? 'status' : 'firstName', value: '' })}><option value="CONTACT">Contact field</option><option value="LEAD">Lead field</option><option value="FIXED">Fixed value</option></CFormSelect></CCol><CCol md={6}>{mapping.source === 'FIXED' ? <><CFormLabel>Fixed value</CFormLabel><CFormInput aria-label={`Fixed value ${index + 1}`} value={mapping.value} onChange={(event) => updateMapping(index, { value: event.target.value })}/></> : <><CFormLabel>Field</CFormLabel><CFormSelect aria-label={`Variable field ${index + 1}`} value={mapping.field} onChange={(event) => updateMapping(index, { field: event.target.value })}>{(mapping.source === 'CONTACT' ? CONTACT_FIELDS : LEAD_FIELDS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</CFormSelect></>}</CCol></CRow>) : <p className="text-muted">This template has no variables.</p>}</>}
      <div className="crm-form-actions"><CButton onClick={create} disabled={busy || !templateId}>{busy ? 'Creating…' : 'Create draft'}</CButton></div></>}</CCardBody></CCard> : <><CCard className="crm-section"><CCardHeader>Draft: {broadcast.templateName}</CCardHeader><CCardBody><p>Version {broadcast.version}. Template: {broadcast.templateLanguage} · {broadcast.templateCategory}</p><div className="crm-actions"><CButton onClick={prepare} disabled={busy}>{busy ? 'Preparing…' : 'Prepare recipients'}</CButton><CButton color="danger" variant="outline" onClick={remove} disabled={busy}>Delete draft</CButton></div></CCardBody></CCard>
      <CCard className="crm-section"><CCardBody><div className="crm-definition-grid"><div><dt>Total candidates</dt><dd>{Object.values(broadcast.preparationCounts || {}).filter((value) => typeof value === 'number').reduce((sum, value) => sum + value, 0)}</dd></div><div><dt>Eligible</dt><dd>{broadcast.preparationCounts?.eligible || 0}</dd></div><div><dt>Skipped</dt><dd>{broadcast.preparationCounts?.skipped || 0}</dd></div><div><dt>Rejected</dt><dd>{broadcast.preparationCounts?.rejected || 0}</dd></div></div>{Object.entries(broadcast.preparationCounts?.byReason || {}).map(([reason, count]) => <span className="me-3" key={reason}>{reason}: {count}</span>)}</CCardBody></CCard>
      <CCard className="crm-section"><CCardHeader>{['ELIGIBLE', 'SKIPPED', 'REJECTED'].map((status) => <CButton key={status} className="me-2" variant={tab === status ? undefined : 'outline'} onClick={() => chooseTab(status)}>{status}</CButton>)}</CCardHeader><CCardBody>{busy ? <LoadingState/> : !recipients.length ? <EmptyState title="No recipient previews in this category" /> : <><CTable responsive><CTableHead><CTableRow><CTableHeaderCell>Contact</CTableHeaderCell><CTableHeaderCell>Phone</CTableHeaderCell><CTableHeaderCell>Rendered preview</CTableHeaderCell><CTableHeaderCell>Reason</CTableHeaderCell></CTableRow></CTableHead><CTableBody>{recipients.map((recipient) => <CTableRow key={recipient.id}><CTableDataCell>{recipient.displayName || 'Unnamed Contact'}</CTableDataCell><CTableDataCell>{recipient.normalizedPhone || '—'}</CTableDataCell><CTableDataCell>{recipient.renderedText || '—'}</CTableDataCell><CTableDataCell>{recipient.exclusionReason || '—'}</CTableDataCell></CTableRow>)}</CTableBody></CTable><PaginationControls pagination={pagination} onPage={(page) => loadRecipients(tab, page)} /></>}</CCardBody></CCard></>}</main>;
};

export default WhatsAppBroadcasts;
