import React from 'react';
import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import CounsellingReports from './index';
import { useAuth } from '../../auth/AuthProvider';
import { getCounsellingReportOutcomes, getCounsellingReportProductivity, getCounsellingReportSummary, listCounsellorOptions, listCounsellingReportFollowUps } from '../../services/Apis/crm';

jest.mock('../../auth/AuthProvider', () => ({ useAuth: jest.fn() }));
jest.mock('../../services/Apis/crm', () => ({ getCounsellingReportSummary: jest.fn(), getCounsellingReportOutcomes: jest.fn(), getCounsellingReportProductivity: jest.fn(), listCounsellingReportFollowUps: jest.fn(), listCounsellorOptions: jest.fn() }));
const summary = { activeLeads: 4, leadsWithoutPendingFollowUp: 1, followUpsCreated: 5, pending: 2, overdue: 1, completed: 3, cancelled: 1, completionRate: 0.75, completedOnTime: 2, completedLate: 1, averageCompletionDelayMinutes: 12.5, nextFollowUpCreationRate: 0.5, leadStatusChangesFromCompletion: 2, reminders: { overdue: 1, dueNow: 2, dueSoon: 3 } };
const rows = [{ id: 'f1', contact: { displayName: 'Asha', normalizedPhone: '+919999999999' }, assignedCounsellorId: 'u2', type: 'CALL', priority: 'HIGH', status: 'COMPLETED', dueAt: '2026-07-19T08:00:00Z', completedAt: '2026-07-19T08:00:00Z', outcome: 'CONNECTED_INTERESTED' }];
beforeEach(() => { jest.clearAllMocks(); useAuth.mockReturnValue({ user: { id: 'admin', role: 'SUPER_ADMIN' } }); getCounsellingReportSummary.mockResolvedValue({ data: { data: summary } }); getCounsellingReportOutcomes.mockResolvedValue({ data: { data: { outcomes: { CONNECTED_INTERESTED: 2, NO_ANSWER: 1 } } } }); getCounsellingReportProductivity.mockResolvedValue({ data: { data: [{ counsellor: { id: 'u2', displayName: 'Counsellor' }, metrics: summary }] } }); listCounsellingReportFollowUps.mockResolvedValue({ data: { data: rows, pagination: { page: 1, totalPages: 1, hasNext: false, hasPrevious: false } } }); listCounsellorOptions.mockResolvedValue({ data: { data: [{ id: 'u2', displayName: 'Counsellor' }] } }); });

test('Super Admin sees summary, outcomes, productivity and drill-down', async () => { render(<CounsellingReports />); expect((await screen.findAllByText('Active Leads')).length).toBeGreaterThan(0); expect(screen.getAllByText('CONNECTED_INTERESTED').length).toBeGreaterThan(0); expect(screen.getAllByText('Counsellor').length).toBeGreaterThan(0); expect(screen.getByText('Asha')).toBeInTheDocument(); expect(screen.getByLabelText('Report counsellor')).toBeInTheDocument(); });
test('date filters are converted to timezone-qualified ISO and reset pagination', async () => { render(<CounsellingReports />); await screen.findByText('Asha'); fireEvent.change(screen.getByLabelText('Date from'), { target: { value: '2026-07-01' } }); fireEvent.change(screen.getByLabelText('Date to'), { target: { value: '2026-07-19' } }); await waitFor(() => expect(getCounsellingReportSummary).toHaveBeenLastCalledWith(expect.objectContaining({ dateFrom: expect.stringMatching(/Z$/), dateTo: expect.stringMatching(/Z$/) }))); expect(listCounsellingReportFollowUps).toHaveBeenLastCalledWith(expect.objectContaining({ page: 1 })); });
test('Counsellor sees only self view and no counsellor selector', async () => { useAuth.mockReturnValue({ user: { id: 'u2', role: 'COUNSELLOR' } }); render(<CounsellingReports />); await screen.findByText('Asha'); expect(screen.queryByLabelText('Report counsellor')).not.toBeInTheDocument(); expect(getCounsellingReportSummary).toHaveBeenCalledWith(expect.not.objectContaining({ assignedCounsellorId: expect.anything() })); });
test('clearing filters and pagination refresh drill-down', async () => { render(<CounsellingReports />); await screen.findByText('Asha'); fireEvent.change(screen.getByLabelText('Date from'), { target: { value: '2026-07-01' } }); fireEvent.click(screen.getByText('Clear filters')); await waitFor(() => expect(getCounsellingReportSummary).toHaveBeenLastCalledWith({})); });
test('shows loading, empty and controlled API errors', async () => { getCounsellingReportSummary.mockRejectedValueOnce({ response: { data: { error: { message: 'Report unavailable' } } } }); render(<CounsellingReports />); expect(await screen.findByText('Report unavailable')).toBeInTheDocument(); });
