import React, { useCallback, useEffect, useState } from 'react';
import { CAlert, CButton, CCard, CCardBody, CCol, CFormInput, CFormLabel, CFormSelect, CRow, CTable } from '@coreui/react';
import { useAuth } from '../../auth/AuthProvider';
import { createStaffUser, listStaffUsers, resetStaffPassword, updateStaffUser } from '../../services/Apis/crm';
import { apiFieldErrors, apiMessage, ErrorState, formatDate, LoadingState, PaginationControls, StatusBadge } from '../Crm/common';
import '../Crm/crm.css';

const blank = { displayName: '', email: '', role: 'COUNSELLOR', temporaryPassword: '', confirmTemporaryPassword: '' };
const StaffUsers = () => {
  const { logout } = useAuth();
  const [items, setItems] = useState([]); const [pagination, setPagination] = useState(null); const [page, setPage] = useState(1);
  const [form, setForm] = useState(blank); const [reset, setReset] = useState({}); const [editing, setEditing] = useState({});
  const [filters, setFilters] = useState({ search: '', role: '', isActive: '' }); const [query, setQuery] = useState({});
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [fieldErrors, setFieldErrors] = useState({});
  const load = useCallback(async () => { setLoading(true); try { const response = await listStaffUsers({ page, pageSize: 25, ...query }); setItems(response.data.data); setPagination(response.data.pagination); } catch (requestError) { setError(apiMessage(requestError)); } finally { setLoading(false); } }, [page, query]);
  useEffect(() => { load(); }, [load]);
  const run = async (action, success) => { if (busy) return null; setBusy(true); setError(''); setMessage(''); setFieldErrors({}); try { const response = await action(); setMessage(success); await load(); return response; } catch (requestError) { setError(apiMessage(requestError)); setFieldErrors(apiFieldErrors(requestError)); return null; } finally { setBusy(false); } };
  const create = async (event) => { event.preventDefault(); if (await run(() => createStaffUser(form), 'Staff user created. Temporary password values were cleared.')) setForm(blank); };
  const save = async (item) => { const response = await run(() => updateStaffUser(item.id, { version: item.version, ...(editing[item.id] || {}) }), 'Staff user updated.'); if (response?.data?.data?.reauthenticationRequired) await logout(); };
  const resetPassword = async (item) => { const password = reset[item.id] || ''; if (await run(() => resetStaffPassword(item.id, { temporaryPassword: password, confirmTemporaryPassword: password }), 'Temporary password set; sessions revoked.')) setReset((current) => ({ ...current, [item.id]: '' })); };
  if (loading) return <LoadingState label="Loading staff users…"/>;
  return <main className="crm-page"><div className="crm-page-header"><div><h1>Staff users</h1><p>Create and administer Super Admin and Counsellor accounts.</p></div></div>{message && <CAlert color="success">{message}</CAlert>}{error && <ErrorState message={error} onRetry={load}/>} 
    <CCard className="crm-section"><CCardBody><form onSubmit={(event) => { event.preventDefault(); setQuery(Object.fromEntries(Object.entries(filters).filter(([, value]) => value !== ''))); setPage(1); }}><CRow className="g-3"><CCol md={6}><CFormLabel>Search staff</CFormLabel><CFormInput value={filters.search} onChange={(e) => setFilters((current) => ({ ...current, search: e.target.value }))}/></CCol><CCol md={3}><CFormLabel>Role</CFormLabel><CFormSelect value={filters.role} onChange={(e) => setFilters((current) => ({ ...current, role: e.target.value }))}><option value="">All</option><option>SUPER_ADMIN</option><option>COUNSELLOR</option></CFormSelect></CCol><CCol md={3}><CFormLabel>Active state</CFormLabel><CFormSelect value={filters.isActive} onChange={(e) => setFilters((current) => ({ ...current, isActive: e.target.value }))}><option value="">All</option><option value="true">Active</option><option value="false">Inactive</option></CFormSelect></CCol></CRow><div className="crm-form-actions"><CButton type="submit">Apply filters</CButton></div></form></CCardBody></CCard>
    <CCard className="crm-section"><CCardBody><h2 className="h5">Create staff user</h2><form onSubmit={create}><CRow className="g-3">{[['displayName','Display name','text'],['email','Email','email'],['temporaryPassword','Temporary password','password'],['confirmTemporaryPassword','Confirm password','password']].map(([field,label,type]) => <CCol md={3} key={field}><CFormLabel htmlFor={`staff-${field}`}>{label}</CFormLabel><CFormInput id={`staff-${field}`} type={type} required value={form[field]} onChange={(e) => setForm((current) => ({ ...current, [field]: e.target.value }))} invalid={Boolean(fieldErrors[field])}/></CCol>)}<CCol md={3}><CFormLabel>Role</CFormLabel><CFormSelect value={form.role} onChange={(e) => setForm((current) => ({ ...current, role: e.target.value }))}><option>COUNSELLOR</option><option>SUPER_ADMIN</option></CFormSelect></CCol></CRow><div className="crm-form-actions"><CButton type="submit" disabled={busy}>Create user</CButton></div></form></CCardBody></CCard>
    <CCard className="crm-section"><CCardBody className="p-0"><CTable responsive hover><thead><tr><th>User</th><th>Role</th><th>Status</th><th>Must change</th><th>Login / timestamps</th><th>Manage</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><CFormInput aria-label="Display name" value={editing[item.id]?.displayName ?? item.displayName} onChange={(e) => setEditing((current) => ({ ...current, [item.id]: { ...current[item.id], displayName: e.target.value } }))}/><CFormInput className="mt-1" aria-label="Email" value={editing[item.id]?.email ?? item.email} onChange={(e) => setEditing((current) => ({ ...current, [item.id]: { ...current[item.id], email: e.target.value } }))}/></td><td>{item.role}</td><td><StatusBadge value={item.isActive ? 'ACTIVE' : 'INACTIVE'}/></td><td>{item.mustChangePassword ? 'Yes' : 'No'}</td><td>Login: {formatDate(item.lastLoginAt, true)}<br/>Created: {formatDate(item.createdAt, true)}<br/>Updated: {formatDate(item.updatedAt, true)}</td><td><div className="d-flex gap-2 flex-wrap"><CButton size="sm" onClick={() => save(item)}>Save</CButton><CButton size="sm" variant="outline" color={item.isActive ? 'danger' : 'success'} onClick={() => run(() => updateStaffUser(item.id, { version: item.version, isActive: !item.isActive }), item.isActive ? 'User deactivated.' : 'User reactivated.')}>{item.isActive ? 'Deactivate' : 'Reactivate'}</CButton><CFormInput aria-label="New temporary password" type="password" placeholder="Temporary password" value={reset[item.id] || ''} onChange={(e) => setReset((current) => ({ ...current, [item.id]: e.target.value }))}/><CButton size="sm" variant="outline" disabled={!reset[item.id]} onClick={() => resetPassword(item)}>Reset password</CButton></div></td></tr>)}</tbody></CTable></CCardBody></CCard><PaginationControls pagination={pagination} onPage={setPage}/></main>;
};
export default StaffUsers;
